### PR TITLE
Add check before building overview page

### LINKED ISSUE #76: BIH clean up traces back when stitch fails
this happens during BIH-clean-up after stitching fails, and then of course there is no cache dir to clean up and the variable is not defined yet:

```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/gits/docserv/src/docserv/bih.py", line 147, in __del__
    self.cleanup()
  File "/gits/docserv/src/docserv/bih.py", line 105, in cleanup
    self.deliverable_cache_base_dir,
AttributeError: 'BuildInstructionHandler' object has no attribute 'deliverable_cache_base_dir'
```

### PR DESCRIPTION
**Pull request by svenseeberg**
* When the XML config is invalid, the variable `deliverable_cache_base_dir` is not set. Subsequently,
  building the overview page fails. This commit adds a check for the existence of the `deliverable_cache_base_dir` variable (attribute).
* Fixes #76.

### CODE REVIEW

**Comment by tomschr** [comment]
@sknorr I committed 8847dd3 which should fix the UnboundLocalError.

**Comment by sknorr** [comment]
i don't think 8847dd3 worked, @tomschr ...

**Comment by tomschr** [comment]
Oh, really? Do you get a different error? Can you paste it here? Thanks!

**Comment by sknorr** [comment]
ah, right, i missed this: the complaint is the same but about `commands` now.

**Comment by tomschr** [comment]
Ok, thanks. After a second look, I think I found the commands issue. The dictionary has to be defined *before* the if clause. See the above commit.

**Comment by sknorr** [comment]
@tomschr i think you've got to get a working docserv setup, doing `git pull && docserv` all the time is sort of annoying. and the next issue is `sync_source_tmp`...

**Comment by tomschr** [comment]
Yeah, actually I was trying to do that. I thought it would be only a minor thing (undefined variables), but it seems, it's a bigger thing. Let me check that.

**Comment by svenseeberg** [comment]
I'll take a look at this later.

**Comment by svenseeberg** [comment]
Okay, I'm sorry. I was a little hasty in my initial solution. It does not make sense to run rsync if creating the overview page didn't work. Therefore the rsync commands are now also included in the if block.

I also amended the code at the end of the dict generation with a new check. If the dict is empty, the cleanup procedure will exit immediately.

**Comment by sknorr** [comment]
#111 addresses this -> closing.

**Comment by eliroca** [comment]
Actually #176 fixed this.

**Pull request closed without merging**
